steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/recommendai:$COMMIT_SHA', 
      '.'
    ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/recommendai:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'recommendai'
    - '--image=gcr.io/$PROJECT_ID/recommendai:$COMMIT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--port=3000'
    - '--memory=1Gi'
    - '--cpu=1'
    - '--min-instances=0'
    - '--max-instances=10'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances=$PROJECT_ID:us-central1:recommendai-db'
    - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest'

images:
  - gcr.io/$PROJECT_ID/recommendai:$COMMIT_SHA