name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate Prisma client
      run: npx prisma generate
    
    - name: Build application
      run: npm run build
    
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
    
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy recommendai \
          --source . \
          --region us-central1 \
          --platform managed \
          --port 3000 \
          --memory 1Gi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --allow-unauthenticated \
          --add-cloudsql-instances recommendai-prod:us-central1:recommendai-db \
          --set-secrets DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest \
          --project recommendai-prod
    
    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe recommendai --region=us-central1 --format="value(status.url)" --project recommendai-prod)
        echo "🚀 Deployment successful!"
        echo "Service URL: $SERVICE_URL"